# Generated by Django 4.0 on 2021-12-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_shopcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_grade',
            field=models.CharField(choices=[('Base', 'Base'), ('Standard', 'Standard'), ('Premium', 'Premium')], default='Standard', max_length=50),
        ),
    ]
